[[trace.node]]
node = "embedding"
id = 0
tag = "text_encoder_embedding"

[[trace.node]]
node = "embedding_1"
id = 1
tag = "text_encoder_embedding_1"

[[trace.node]]
node = "add"
id = 2
tag = "text_encoder_add"

[[trace.node]]
node = "rsqrt"
id = 3
tag = "text_encoder_rsqrt"

[[trace.node]]
node = "addmm"
id = 4
tag = "text_encoder_addmm"

[[trace.node]]
node = "addmm_1"
id = 5
tag = "text_encoder_addmm_1"
