[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "omni-qwen3-omni-30b-a3b-instruct"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["numpy", "torch", "transformers", "soundfile>=0.13.1", "torchaudio", "opencv-python", "Pillow"]

[tool.setuptools]
packages = ["examples.models.omni.qwen3-omni-30b-a3b-instruct", "examples.models.omni.qwen3-omni-30b-a3b-instruct.media"]
package-dir = {"" = ".", "examples.models.omni.qwen3-omni-30b-a3b-instruct" = "."}
