[[trace]]
node = "convolution"
id = 0
tag = "conv1_out_nchw"

[[trace]]
node = "relu"
id = 1
tag = "relu1_out_nchw"

[[trace]]
node = "convolution_1"
id = 2
tag = "conv2_out_nchw"

[[trace]]
node = "relu_1"
id = 3
tag = "relu2_out_nchw"

[[trace]]
node = "view"
id = 4
tag = "flatten_out"

[[trace]]
node = "addmm"
id = 5
tag = "fc1_out"

[[trace]]
node = "relu_2"
id = 6
tag = "relu3_out"

[[trace]]
node = "addmm_1"
id = 7
tag = "fc2_out"

[[trace]]
node = "relu_3"
id = 8
tag = "relu4_out"

[[trace]]
node = "addmm_2"
id = 9
tag = "fc3_out"
