[[trace]]
node = "arg2_1"
id = 0
tag = "input_nchw"
layout = "nchw"

[[trace]]
node = "convolution"
id = 1
tag = "conv1_out_nchw"
layout = "nchw"

[[trace]]
node = "relu"
id = 2
tag = "relu1_out_nchw"
layout = "nchw"

[[trace]]
node = "getitem"
id = 3
tag = "pool1_out_nchw"
layout = "nchw"

[[trace]]
node = "convolution_1"
id = 4
tag = "conv2_out_nchw"
layout = "nchw"

[[trace]]
node = "relu_1"
id = 5
tag = "relu2_out_nchw"
layout = "nchw"

[[trace]]
node = "getitem_2"
id = 6
tag = "pool2_out_nchw"
layout = "nchw"

[[trace]]
node = "view"
id = 7
tag = "flatten_out"
layout = "nc"

[[trace]]
node = "addmm"
id = 8
tag = "fc1_out"
layout = "nc"

[[trace]]
node = "relu_2"
id = 9
tag = "relu3_out"
layout = "nc"

[[trace]]
node = "addmm_1"
id = 10
tag = "fc2_out"
layout = "nc"

[[trace]]
node = "relu_3"
id = 11
tag = "relu4_out"
layout = "nc"

[[trace]]
node = "addmm_2"
id = 12
tag = "fc3_out"
layout = "nc"
