cmake_minimum_required(VERSION 3.22)
project(BuckyballWorkerMux LANGUAGES CXX)
find_package(Threads REQUIRED)
add_executable(worker-mux mux.cpp)
target_compile_features(worker-mux PRIVATE cxx_std_17)
target_compile_definitions(worker-mux PRIVATE _GNU_SOURCE)
target_compile_options(worker-mux PRIVATE -Wall -Wextra -Werror)
target_link_libraries(worker-mux PRIVATE Threads::Threads)
target_link_options(worker-mux PRIVATE -static)
install(TARGETS worker-mux RUNTIME DESTINATION bin)
add_executable(dax-check dax-check.cpp)
target_compile_features(dax-check PRIVATE cxx_std_17)
target_compile_definitions(dax-check PRIVATE _GNU_SOURCE)
target_compile_options(dax-check PRIVATE -Wall -Wextra -Werror)
target_link_options(dax-check PRIVATE -static)
install(TARGETS dax-check RUNTIME DESTINATION bin)
