[[trace]]
node = "embedding"
id = 0
tag = "embedding"

[[trace]]
node = "embedding_1"
id = 1
tag = "embedding_1"

[[trace]]
node = "mul_1"
id = 2
tag = "mul_1"

[[trace]]
node = "pow_1"
id = 3
tag = "pow_1"

[[trace]]
node = "mean"
id = 4
tag = "mean"

[[trace]]
node = "add_1"
id = 5
tag = "add_1"
