[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "whisper-model"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["huggingface-hub"]

[tool.setuptools]
packages = ["stack.models.models.whisper"]
package-dir = {"stack.models.models.whisper" = "."}

[tool.setuptools.package-data]
"stack.models.models.whisper" = ["configs/model.toml"]
