[[trace]]
node = "sin"
id = 100
tag = "unet_sin"

[[trace]]
node = "cos"
id = 101
tag = "unet_cos"

[[trace]]
node = "cat"
id = 102
tag = "unet_cat"

[[trace]]
node = "convolution"
id = 103
tag = "unet_convolution"

[[trace]]
node = "addmm"
id = 104
tag = "unet_addmm"

[[trace]]
node = "convolution_1"
id = 105
tag = "unet_convolution_1"
