#!/usr/bin/env bash

# exit script if any command fails
set -e
set -o pipefail

ROOT=$(git rev-parse --show-toplevel)
BUDDY_MLIR_DIR=${ROOT}/thirdparty/buddy-mlir

# get helpful utilities
source ${ROOT}/scripts/utils.sh

source ${ROOT}/env.sh
pip install -r ${BUDDY_MLIR_DIR}/requirements.txt

cd ${BUDDY_MLIR_DIR}
git submodule update --init llvm

mkdir -p llvm/build && cd llvm/build
cmake -G Ninja ../llvm \
  -DLLVM_ENABLE_PROJECTS="mlir;clang" \
  -DLLVM_TARGETS_TO_BUILD="host;RISCV" \
  -DLLVM_ENABLE_ASSERTIONS=ON \
  -DCMAKE_BUILD_TYPE=RELEASE \
  -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
  -DPython3_EXECUTABLE=$(which python3)
ninja #check-mlir check-clang

cd ${BUDDY_MLIR_DIR}
mkdir -p build && cd build
cmake -G Ninja .. \
  -DMLIR_DIR=$PWD/../llvm/build/lib/cmake/mlir \
  -DLLVM_DIR=$PWD/../llvm/build/lib/cmake/llvm \
  -DLLVM_ENABLE_ASSERTIONS=ON \
  -DCMAKE_BUILD_TYPE=RELEASE \
  -DBUDDY_MLIR_ENABLE_PYTHON_PACKAGES=ON \
  -DPython3_EXECUTABLE=$(which python3) \
  -DPython_EXECUTABLE=$(which python3)
ninja
#ninja check-buddy

replace_content ${ROOT}/env.sh install-compiler "# line auto-generated by $0
export BUDDY_MLIR_BUILD_DIR=${BUDDY_MLIR_DIR}/build
export LLVM_MLIR_BUILD_DIR=${BUDDY_MLIR_DIR}/llvm/build
export PYTHONPATH=${BUDDY_MLIR_DIR}/llvm/build/tools/mlir/python_packages/mlir_core:${BUDDY_MLIR_DIR}/build/python_packages:\${PYTHONPATH}"


export BUDDY_MLIR_BUILD_DIR=${BUDDY_MLIR_DIR}/build
export LLVM_MLIR_BUILD_DIR=${BUDDY_MLIR_DIR}/llvm/build
export PYTHONPATH=${BUDDY_MLIR_DIR}/llvm/build/tools/mlir/python_packages/mlir_core:${BUDDY_MLIR_DIR}/build/python_packages:\${PYTHONPATH}
