cmake_minimum_required(VERSION 3.22)
project(ModelLoader LANGUAGES C CXX)
get_filename_component(STACK_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../.." ABSOLUTE)
set(BUDDY_SOURCE "${STACK_ROOT}/compiler/thirdparty/buddy-mlir")
find_package(LLVM REQUIRED CONFIG PATHS "${BUDDY_SOURCE}/llvm/build/lib/cmake/llvm" NO_DEFAULT_PATH)
find_program(FLATC_EXECUTABLE flatc REQUIRED)
add_subdirectory("${BUDDY_SOURCE}/runtime/rax" rax)
add_executable(load-model main.cpp)
target_compile_features(load-model PRIVATE cxx_std_17)
target_include_directories(load-model PRIVATE "${BUDDY_SOURCE}/runtime/include" ${LLVM_INCLUDE_DIRS})
target_link_libraries(load-model PRIVATE buddy_rax LLVMSupport)
