[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "poly-qwen3-8b"
version = "0.1.0"
requires-python = ">=3.12"

[tool.setuptools]
packages = ["examples.models.poly.qwen3-8b", "examples.models.poly.qwen3-8b.permute", "examples.models.poly.qwen3-8b.quant", "examples.models.poly.qwen3-8b.trace", "examples.models.poly.qwen3-8b.configs"]
package-dir = {"" = ".", "examples.models.poly.qwen3-8b" = "."}
