def add_arguments(parser):
    parser.add_argument("--duration-s", type=int, default=4)
    parser.add_argument("--fps", type=int, default=24)
    parser.add_argument("--height", type=int, default=768)
    parser.add_argument("--width", type=int, default=1344)
    parser.add_argument("--latent-c", type=int, default=24)
    parser.add_argument("--audio-latent-c", type=int, default=32)
    parser.add_argument("--text-dim", type=int, default=5120)
    parser.add_argument("--text-len", type=int, default=512)
    parser.add_argument("--sample-rate", type=int, default=32000)
    parser.add_argument("--denoise-steps", type=int, default=30)
    parser.add_argument("--video-shift", type=float, default=12.0)
    parser.add_argument("--frames", type=int)
    parser.add_argument("--latent-t", type=int)
    parser.add_argument("--latent-h", type=int)
    parser.add_argument("--latent-w", type=int)
    parser.add_argument("--audio-latent-t", type=int)
