[[trace.node]]
node = "convolution"
id = 0
tag = "convolution"

[[trace.node]]
node = "convolution_1"
id = 1
tag = "convolution_1"

[[trace.node]]
node = "convolution_2"
id = 2
tag = "convolution_2"

[[trace.node]]
node = "convolution_3"
id = 3
tag = "convolution_3"

[[trace.node]]
node = "convolution_4"
id = 4
tag = "convolution_4"

[[trace.node]]
node = "addmm"
id = 5
tag = "addmm"

[[trace.node]]
node = "addmm_1"
id = 6
tag = "addmm_1"

[[trace.node]]
node = "addmm_2"
id = 7
tag = "addmm_2"
